### ISSUE TITLE
<input size="10"> is not big enough to hold 10 characters

### ISSUE THREAD

**Issue by rothskeller** [HewlettPackard/grommet#1]
Try UH4ACP0150 as example input to see this.
Reported from CI Manager USB Key generator, http://crauth.usa.hp.com/cim-usb-key/

**Comment by mattfarina** [comment]
@rothskeller A couple quick questions...

1. What is the context for `<input size="10">`? I don't see that in the grommet codebase.
2. The link you shared is not publicly accessible. Do you have an example that is publicly accessible?

**Comment by rothskeller** [comment]
I reported this while generating a web tool using grommet (not publicly accessible, as you noted).  The tool presents a Form, and one of the FormFields accepts a serial number.  The serial number is 10 characters, all in uppercase, and I used size="10" in order to make the entry field an appropriate size.  However, when 10 uppercase characters were entered in it, only 8½ actually fit.  There was a similar problem with a license key field, size="29", only 25½ actually fit.

I regret that I don't have a publicly accessible example of this at the moment, but I imagine you could easily duplicate it on any form with an input that sets a size= value.  Just enter that many uppercase letters into it and you'll see they don't all fit.

**Comment by bryanjacquot** [comment]
@ericsoderberghp I just looked at the form fields in the documentation and the form fields don't have a size parameter.  I set a size value on the input field by editing the HTML in the browser, and it seemed to be ignored.  I'm wondering if the new Form layouts render this no longer an issue as the forms seem to respond to the display appropriately.

**Comment by ericsoderberghp** [comment]
@bryanjacquot you are correct. The FormField controls the size of the input. Currently, all inputs are the same width.

**Comment by rothskeller** [comment]
OK, then in that case this issue is outdated.
