### ISSUE TITLE
IE 11:  the 'Enclosure' detailed page has format issues.

### ISSUE THREAD

**Issue by tran2519** [HewlettPackard/grommet#106]
![image](https://cloud.githubusercontent.com/assets/13039669/8911064/0433f244-343f-11e5-9ddd-4a691ec3c0ac.png)

Chrome displays it correctly:

![image](https://cloud.githubusercontent.com/assets/13039669/8911099/3d7de898-343f-11e5-9f6d-e5381539191d.png)

**Comment by alansouzati** [comment]
Fixed. Thanks for reporting this @tran2519
