### ISSUE TITLE
Format issue, seen in Firefox version 39

### ISSUE THREAD

**Issue by tran2519** [HewlettPackard/grommet#118]
![image](https://cloud.githubusercontent.com/assets/13039669/9047304/dfc248fa-39e5-11e5-8a06-f637d4fe26a7.png)

**Comment by tran2519** [comment]
The format issue is also seen in Chrome and IE11

**Comment by alansouzati** [comment]
I believe this should be fixed, I was not able to reproduce in the first place, but I guess I know what is going on. Could you please check it again? Thanks for reporting this.

**Comment by tran2519** [comment]
It's fixed.  Thanks.
