### ISSUE TITLE
Distribution not covering text

### ISSUE THREAD

**Issue by afong94** [HewlettPackard/grommet#119]
For a distribution with 1 item, the box isn't filled with color and only shows a small bar.
![capture](https://cloud.githubusercontent.com/assets/5715687/9065938/a4c01ff8-3a89-11e5-9948-1dba829c358e.PNG)

**Comment by ericsoderberghp** [comment]
This has been fixed in commit 49a36620b7ef515392d5422790aae7b29f81c005.
