### ISSUE TITLE
Width issue

### ISSUE THREAD

**Issue by tran2519** [HewlettPackard/grommet#120]
Chrome and IE 11
![image](https://cloud.githubusercontent.com/assets/13039669/9066489/d795c768-3a8c-11e5-9d49-41ba8c5c8321.png)

Firefox
![image](https://cloud.githubusercontent.com/assets/13039669/9066540/29430cc4-3a8d-11e5-90ab-17dfed3322b2.png)

**Comment by sudesh-gama** [comment]
.box--pad-horizontal-medium {
    padding-left: 16px;
    padding-right: 16px;
}
default padding is 24px reduced to 16px hope this is the right solution

**Comment by ericsoderberghp** [comment]
The medium padding is 24px (actually $inuit-base-spacing-unit) throughout to ensure that everything aligns well. Changing just this location to 16px will break the alignment elsewhere. I think we need a different solution for this issue.

**Comment by sudesh-gama** [comment]
Hi All,
<Grommet.Menu direction is not working inside <Grommet.Header>, what is the reason.? is there any other way to put inline menu in the Grommet Header

**Comment by sudesh-gama** [comment]
hi all,

Inside the <Grommet.Header/> <Grommet.Menu> alignment is not working, what is the reason, is there any other way to do it

**Comment by sudesh-gama** [comment]
hi all indie grommet.header menu alignment is not working any specific reason, or is there any other way to use it.

Regards,
Sudesh

**Comment by ericsoderberghp** [comment]
Sudesh, is your question about Header Menu alignment part of this issue or a separate issue? If it is separate, can you add a new issue, along with a screenshot and more detail?

**Comment by ericsoderberghp** [comment]
The Grommet site was changed a while ago to not have separate scroll regions for the documentation.
