### ISSUE TITLE
Clicking on the SearchInput component suggestions does not update the SearchInput value

### ISSUE THREAD

**Issue by stephanbochet** [HewlettPackard/grommet#127]
Steps for recreating the issue: 

1) Click on the Example SearchInput in the following link : http://grommet.io/docs/develop/searchinput
2) Insert the letter  "f" into the search box.
3) Click on the suggestion "four". 

Clicking on the four will not update the value of the SearchInput component.

![image](https://cloud.githubusercontent.com/assets/13683178/9120599/23658902-3c4b-11e5-98aa-1cb71f8edc95.png)

**Comment by ericsoderberghp** [comment]
Fixed in 098924e8b9d1cbdc8796c4a54e09d5a321edc9ec.
