### ISSUE TITLE
(minor) on ticker update the update steals focus from current mouseover

### ISSUE THREAD

**Issue by kylebyerly-hp** [HewlettPackard/grommet#145]
On ticker update the value overlay is updated on the far right, even if I'm currently moused over a column.

It will not resume the mouseover number unless I move out of the vertical column and back.

http://grommet.io/docs/develop/chart
Ticker

**Comment by ericsoderberghp** [comment]
Fixed in 396724fbcb34f23bfcd59493eabe71b7f01861c2.
