### ISSUE TITLE
Form on Role example has odd bouncing

### ISSUE THREAD

**Issue by kylebyerly-hp** [HewlettPackard/grommet#147]
On the Role example in Form, selecting Full instead of specialized results in the checkboxes bouncing.

This behavior is seen on chrome, firefox, and IE11. It is much more pronounced in IE11.

Middle of the bounce.
![bouncing](https://cloud.githubusercontent.com/assets/13527666/9182862/042811c4-3f69-11e5-8ffc-87b1f8d03503.png)

After this is slides up smoothly, as expected (since the select behavior is a slide down).

**Comment by ericsoderberghp** [comment]
Fixed in commit ddc6555fe9a37561d9f2bee6e583342a3babbdc5.
