### ISSUE TITLE
Spiral Meter doesn't seem to work?

### ISSUE THREAD

**Issue by scottshaffer** [HewlettPackard/grommet#148]
The spiral Meter doesn't look to be working in the latest build.  The exact example off the sample page doesn't work while all the other Meters do.  Maybe there is more setup required for spiral than is listed on the sample page?

**Comment by alansouzati** [comment]
Sorry about that @scottshaffer. When you say latest build, is this the stable build, or Grommet version 0.3.1? Can you paste here your `package.json` dependencies?

**Comment by scottshaffer** [comment]
Yes this is 0.3.1 which I thought was the stable build.  At least I attempted to pull stable and this is what I got.

  "name": "grommet",
  "version": "0.3.1",

  "dependencies": {
    "intl": "^0.1.4",
    "inuit-box-sizing": "~0.2.0",
    "inuit-clearfix": "^0.2.1",
    "inuit-defaults": "~0.2.1",
    "inuit-functions": "~0.2.0",
    "inuit-headings": "~0.3.0",
    "inuit-images": "~0.3.3",
    "inuit-list-bare": "~0.3.0",
    "inuit-lists": "~0.1.0",
    "inuit-mixins": "~0.2.3",
    "inuit-normalize": "~3.0.2",
    "inuit-page": "~0.2.1",
    "inuit-reset": "~0.1.1",
    "inuit-responsive-settings": "~0.1.2",
    "inuit-responsive-tools": "~0.1.1",
    "inuit-shared": "~0.1.5",
    "lodash": "^3.8.0",
    "moment": "^2.8.3",
    "react": "^0.13.1",
    "react-gravatar": "^1.0.0",
    "react-intl": "^1.2.0",
    "react-router": "^0.13.3",
    "react-time": "^2.4.0",
    "reflux": "^0.2.7",
    "superagent": "^1.1.0",
    "yargs": "^3.8.0",
    "gulp": "^3.8.11",
    "gulp-template": "^3.0.0",
    "gulp-install": "^0.4.0",
    "gulp-file": "^0.2.0",
    "mkdirp": "^0.5.1",
    "node-uuid": "^1.4.0"
  },
  "devDependencies": {
    "del": "^1.1.1",
    "expect": "^1.6.0",
    "should": "^6.0.1",
    "css-loader": "^0.14.0",
    "file-loader": "^0.8.1",
    "imports-loader": "^0.6.3",
    "babel-loader": "^5.2.2",
    "sass-loader": "^1.0.2",
    "style-loader": "^0.12.0",
    "json-loader": "^0.5.1",
    "gulp-chug": "^0.4.2",
    "gulp-eslint": "^0.12.0",
    "gulp-minify-css": "^1.1.0",
    "gulp-mocha": "^2.0.1",
    "gulp-live-server": "^0.0.21",
    "gulp-preprocess": "^1.2.0",
    "gulp-react": "^3.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-rsync": "0.0.5",
    "gulp-sass": "^1.3.3",
    "gulp-scss-lint": "^0.2.0",
    "gulp-watch": "^4.2.4",
    "gulp-coveralls": "^0.1.4",
    "gulp-if": "^1.2.5",
    "gulp-git": "^1.2.3",
    "gulp-prompt": "^0.1.2",
    "gulp-bump": "^0.3.0",
    "gulp-jsx-coverage": "^0.1.3",
    "gulp-open": "^0.3.2",
    "gulp-replace": "^0.5.3",
    "node-sass": "^3.2.0",
    "webpack-stream": "^2.0.0",
    "eslint": "^0.21.2",
    "eslint-plugin-react": "^2.4.0",
    "babel": "^5.3.3",
    "babel-eslint": "^3.1.9",
    "babel-core": "^5.6.15",
    "jsdom-no-contextify": "~3.1.0",
    "react-tools": "^0.13.1",
    "run-sequence": "^1.0.2",
    "webpack": "^1.9.11",
    "webpack-dev-server": "^1.8.0",
    "node-libs-browser": "^0.5.0",
    "glob": "^4.3.5",
    "rewire": "^2.3.3",
    "mocha-lcov-reporter": "^0.0.2",
    "selenium-standalone": "^4.2.2",
    "webdriverio": "^2.4.5"
  },

**Comment by alansouzati** [comment]
Sorry I guess i was not clear on what I meant. Can you paste here your application package.json. I just want to double check how are you pulling the stable build.

**Comment by scottshaffer** [comment]
Ah - here is what I have:

  "dependencies": {
    "react": "^0.13.1",
    "grommet": "^0.3.1"
  },

**Comment by alansouzati** [comment]
Yeah, this is not the stable build. Can you replace by this:

```
"grommet": "https://github.com/HewlettPackard/grommet.git#stable"
```

0.3.1 is an actual release.

We need to update the docs page to inform that Spiral only works for stable builds.

Alan

**Comment by scottshaffer** [comment]
OK thanks - you can close this issue.
