### ISSUE TITLE
unable to find ruby and scss-lint in gulp

### ISSUE THREAD

**Issue by samogami** [HewlettPackard/grommet#178]
In windows when I run commands like `gulp dist` in grommet, gulp is unable to find scss-lint

from the command line running `gulp dist`:
...
```
[14:07:54] Starting 'scsslint'...
[scsslint] scsslint skipped!
[scsslint] scss-lint is not installed. Please install ruby and the ruby gem scss-lint.
[14:07:54] Finished 'scsslint' after 3.89 ms
[14:07:54] Finished 'preprocess' after 16 s
```
....

ruby and scss-lint are installed.
```
PS C:\Users\ogamisam\Documents\GitHub\grommet> scss-lint -version
scss-lint 0.41.0
```

**Comment by alansouzati** [comment]
Thanks for reporting that!

Fixed by https://github.com/HewlettPackard/grommet/commit/9aacf42771d522714ed3b17c64c0ec894933e772

It will be part of the next version of Grommet.
