### ISSUE TITLE
clicking enter in password field should log in

### ISSUE THREAD

**Issue by snowymike** [HewlettPackard/grommet#184]
most login pages perform the default form submit action when a user presses enter/return on their keyboard while in the password field.  if a user clicks return while in the 'password' input of the grommet login page, i'd expect that to be equivalent to manually clicking the Log In button

**Comment by Deklin** [comment]
+1

**Comment by bryanjacquot** [comment]
Fixed in https://github.com/HewlettPackard/grommet/commit/89a164aa6e90cd709dcac287c3124a22225b5fd6
