### ISSUE TITLE
When is next release planned

### ISSUE THREAD

**Issue by Deklin** [HewlettPackard/grommet#194]
We are waiting to pull down the login page submit fix, any comment on when the next release is planned?

**Comment by alansouzati** [comment]
Hi @Deklin, we're working on this and we should have a new release the end of this week, or early next week.

In the meantime, you can use Grommet stable, which gets updated every time a successful build is pushed to the master. To get that, update your `package.json` like follows:

```
{
  ...
  dependencies: {
    grommet: 'https://github.com/HewlettPackard/grommet.git#stable'
  }
  ...
}
```

Hopefully this will allow you to get the features you are looking for.

Just remember to run `npm update` to get the new Grommet dependency in your local `node_modules`.
Alan

**Comment by alansouzati** [comment]
Grommet 0.3.7 :+1:
