### ISSUE TITLE
gulp tasks fails at scsslint task

### ISSUE THREAD

**Issue by alansouzati** [HewlettPackard/grommet#27]
After I've updated my gem scss_lint to version 0.39.0 I can't run gulp tasks anymore. The task fails at the scsslint level with the following log:

```
[17:04:14] Finished 'jslint' after 6.6 s
[17:04:14] Starting 'scsslint'...

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Command line usage error
```

If I revert scss_lint to version 0.38 everything works fine.

**Comment by marlonpp** [comment]
+1

**Comment by alansouzati** [comment]
juanfran/gulp-scss-lint#34

**Comment by alansouzati** [comment]
This was due to an outdated version of gulp-scss-lint. I've updated the package.json accordingly.
