### ISSUE TITLE
"Cannot read property 'trim' of undefined" while installing the new tour (medium-app)

### ISSUE THREAD

**Issue by hpjcu** [HewlettPackard/grommet#28]
Hi Alan, I am having trouble installing the new Tour.

After figuring out that I needed to use a new app name after reading the change log (might want to change the Tour install instructions), I was able to properly export the directory using:

             $ grommet export medium-app sample-app

However, after attempting to run "npm install" in my new "sample-app" directory, I received the following message...

![image](https://cloud.githubusercontent.com/assets/12216220/7976834/01166ea6-0a47-11e5-92f0-77c99cf6025b.png)

The installation goes as far as creating the gulp-rsynch directory, then quits. I have attached a picture of the npm debug log section.

![image](https://cloud.githubusercontent.com/assets/12216220/7976861/7c88b1f2-0a47-11e5-8365-e93b7d4559f0.png)

Please note that "npm install" works perfectly in the "server" directory underneath this one.

**Comment by alansouzati** [comment]
Thanks for pointing out the issue with the outdated wiki. I've updated that already.

Also, thanks for such detailed logs, great description on the issue. Based on your logs I see you are still using the `grommet.usa.hp.com` server, could you please run the follow command and try again?

`npm config set registry http://registry.npmjs.org/`

**Comment by hpjcu** [comment]
Alan,

Thanks for the quick reply.

I emailed my response so I could attach the full debug log. It seems to almost get to the end but fails at “webpack”.

Thanks.

Juan

**Comment by alansouzati** [comment]
You're welcome to join [Slack](https://grommet.slack.com). For any communication around Grommet.

**Comment by alansouzati** [comment]
Also, I believe you are having a proxy issue. Can you try to leave a proxied network and try again?

If you are on Windows you can set the proxy like this `set HTTPS_PROXY=https://server:port`.

**Comment by hpjcu** [comment]
Hi Alan,

Tried it both ways, no dice (using “set HTTP_PROXY”).

I have also tried it from home where there is no proxy, and then through the VPN to HP, and it didn’t work either.

Note in the debug log (attached), this time it failed prior to “webpack”, when it reached “inuit-clearfix”.  But it IS failing consistently at that file – I tried it several times.

BTW, it didn’t like HTTPS_PROXY at all.

If the Tour is the same as the Piano site (the medium-app files certainly hint at that), I will just go over there until this works itself out. I am just trying to work my way through the “Menu” component, and there was no mention of “Routes” using React-route, in the prior example app or documentation, but I figured it out by reading the actual code under the new “medium app”. (i.e. to use the standard “Menu.js” component, you have to use Routes.)

Here is the log (upper with proxy set to standard, bottom with proxy set to “”)…

[cid:image001.png@01D09ED3.4070D990]

**Comment by alansouzati** [comment]
Yeah, we still have a lot of documentation/features to cover, specially around workflows and patterns. We are in early stages of development, you are welcome to send Pull Request with updated documentation.

I can't see your logs, if you are replying the email you are receiving from GitHub, I believe they don't support attachments. Feel free to ping me on Slack if you need help debugging this issue.

**Comment by alansouzati** [comment]
I found an issue very similar to yours here npm/npm#7984.

Based on my readings there, it seems to be related to an issue with Node version `0.12.2`. 

They said that downgrading to `0.12.1` works. But, I also tried with `0.12.4` and it works fine.

**Comment by alansouzati** [comment]
As per our talk earlier, updating to `0.12.4` works. So, I'm closing this issue for now.
