### ISSUE TITLE
Enable compression on the website

### ISSUE THREAD

**Issue by mattfarina** [HewlettPackard/grommet#32]
The Grommet website could use some compression (gzip/deflate). According to [PageSpeed](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fwww.grommet.io%2Fdocs%2F&tab=mobile), there is savings to be had on the website.

![image 2015-06-05 at 4 00 10 pm](https://cloud.githubusercontent.com/assets/62991/8014117/fec677f8-0b9b-11e5-84a8-d26e4c36e173.png)

**Comment by alansouzati** [comment]
Thanks for your PR @mattfarina
