### ISSUE TITLE
Make Slack accessible to everyone

### ISSUE THREAD

**Issue by mattfarina** [HewlettPackard/grommet#33]
Right now [Slack access is limited to those with a @hp.com email address](https://grommet.slack.com/signup). Please open this up to all users if it will be the primary form of chat listed in the Readme.

**Comment by alansouzati** [comment]
Please use this link to join without hp domain http://grommet.io/slackin.

The Slack badge has been updated to point to this URL as well.

[![Slack](http://alansouzati.github.io/artic/img/slack-badge.svg)](http://grommet.io/slackin)
