### ISSUE TITLE
Example Server Fails to work

### ISSUE THREAD

**Issue by mattfarina** [HewlettPackard/grommet#34]
The server in `examples/server` fails to work. There are several things going on.

1. The README points to an `examples/tour` directory that isn't present. Is that supposed to do something?
2. When you run `gulp dev` and the server starts and you go to `localhost:8000` it tries to redirect to `localhost:8000/docs` which displays the error:

        Error: ENOENT, stat '/docs/dist/index.html'
        at Error (native)

3. If you look at one of the sample paths in `server.js` you see that `localhost:8000/hello-world/` should work. It just displays a blank screen because of a bunch of errors.

![image 2015-06-05 at 4 30 02 pm](https://cloud.githubusercontent.com/assets/62991/8014603/28beda74-0ba0-11e5-8f2d-62865a8f1e0b.png)

If you visit the paths that don't work like `http://grommet.io/assets/0.2.0/grommet.min.js` you''' get an error like:

    Cannot GET /assets/0.2.0/grommet.min.js

I'd try to clean this up but I'm not entirely sure how it should work and what should be happening.

**Comment by alansouzati** [comment]
Thanks for sharing that, I will add a wiki page on how to run the server.

**Comment by alansouzati** [comment]
Hopefully this is going to be helpful:

https://github.com/HewlettPackard/grommet/wiki/Running-the-example-server

**Comment by alansouzati** [comment]
FYI, I've fixed the not found issues with the assets.

**Comment by mattfarina** [comment]
Aside from the issues I listed on the other issue I'm also finding:

1. `gulp-util`, `deprecated`, `vinyl-fs`, `prelude-ls`, `deep-is`, `fast-levenshtein`, `wordwrap`, `type-check`, `event-stream`, `dargs`, `pretty-data`, `xml2js`, `right-align`, `center-align`, `assert`, `buffer`, `console-browserify`, `constants-browserify`, `crypto-browserify`, `domain-browser`, `events`, `http-browserify`, `https-browserify`, `os-browserify`, `path-browserify`, `punycode`, `process`, `querystring-es3`, `stream-browserify`, `readable-stream`, `string_decoder`, `util`, `timers-browserify`, `tty-browserify`, `url`, `vm-browserify`, `browserify-zlib`, and `levn` are undocumented (or rather not in `package.json`) node dependencies for [creating a dist](https://github.com/HewlettPackard/grommet/wiki/Building-Grommet). Should these be `dependencies` or `devDependencies` in the `package.json`? Have you tried following these instructions from a clean environment?
2. Running `gulp dist` from the `doc` directory also found the missing dependencies `gulp-chug`, `pretty-hrtime`, `chalk`, `semver`, `archy`, `liftoff`, `tildify`, `interpret`, `v8flags`, and `minimist`. Should these be `dependencies` or `devDependencies`? 
3. The readme in the example server directory doesn't specify how this example should be used. How should it be used, independently of the other examples? Or, is it just mean to be a dependency for them? Can the readme be updated to specify exactly how the server example should be used. Maybe a readme in the examples directory outlining how each of them should be used.
4. After I follow the code:
```sh
$ cd ../examples/medium-app
$ gulp dist
```
I get the error:
```
$ gulp dist
module.js:338
    throw err;
          ^
Error: Cannot find module 'grommet/utils/gulp/gulp-tasks'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/mfarina/Code/HP/grommet/examples/medium-app/gulpfile.js:3:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
I can correct this by changing the `gulp.js` file in the `medium-app` to use a relative path for this file (e.g., `var devGulpTasks = require('../../src/utils/gulp/gulp-tasks');`). But then other things start breaking. Is something supposed to instead link the `dist` directory into the `node_modules`?

There is a `package.json` file in the `medium-app` directory. Running `npm install` gives me the error:
```
$ npm install
npm WARN package.json medium-app@0.1.2 No repository field.
npm WARN package.json medium-app@0.1.2 No README data
npm WARN package.json medium-app@0.1.2 No license field.
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: grommet@'>=0.1.2 <0.2.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.2.0","0.2.1","0.2.2"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'medium-app'
npm ERR! notarget

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mfarina/Code/HP/grommet/examples/medium-app/npm-debug.log
```
This is where I stopped. I'm not sure how this should work or I'd submit a pull request.

**Comment by alansouzati** [comment]
Thanks for the feedbacks @mattfarina. We will work on updating the README of the server app, that's definitely a good idea.

Also, to run the `medium-app` inside the examples folder you need to run an `npm link`. We will work on adding a wiki page that explains how to run the medium-app inside Grommet environment. You can [export](https://github.com/HewlettPackard/grommet/wiki/Exporting-examples-from-Grommet) the medium-app to have it working outside for now.

**Comment by alansouzati** [comment]
I've just pushed some changes to the way example apps are handled. Basically I've removed the need to npm link it.

Following your suggestion, I've added a README.md for every sample app we provide. 

 Can you try again? Thanks!

**Comment by mattfarina** [comment]
Two quick things:

1. Is the server example an example or simply a dependency for the other examples? If it's a dependency it could be useful to explicitly say that.
2. When I tried to run the medium app two things happened. First, I didn't have to go beyond the `gulp dev` step in the README.md. Step 2 was just not required. Second, it brought me to a login screen and I don't know the user/pass. I'm not sure from this how to use the medium app.

**Comment by alansouzati** [comment]
Good point. I will update the README.md properly.

**Comment by alansouzati** [comment]
BTW, you do need the Step 2 for the login operation.

**Comment by alansouzati** [comment]
Hey @mattfarina any news on this guy? Do you think we can close this issue?

**Comment by mattfarina** [comment]
I've started to poke at this again. The README in the medium-app didn't work when I just tried them. I'll walk though the wiki guide next week.
