### ISSUE TITLE
Grommet Button cannot be used correctly in the Hello World page

### ISSUE THREAD

**Issue by DanielZhu** [HewlettPackard/grommet#38]
Hi Grommet Team,

I cloned the project and try to play with the demo 'Hello World'. But during my study time, I met some issues after I modified some simple codes on 'grommet\examples\hello-world\index.html'.
```
    var GrommetButton = React.createClass({
      render: function() {
        return (
          // <Grommet.CheckBox id="{item2}" label="Item 2" />
          // <Grommet.CheckBox id="{item3}" label="Item 3" toggle={true} />
          // <Grommet.Button label="Item 1" />
          // <Grommet.Status value="disabled"></Grommet.Status>
          <Grommet.Button label="Action" primary={true} strong={true}></Grommet.Button>
        );
```

Case 1 & 2 works fine, but case 3 & 4 cannot display the button. And gave me the error messages in the console(screenshot attached).

![grommet error](https://cloud.githubusercontent.com/assets/1383798/8079666/c30ac498-0f98-11e5-92a6-e02f7eab1cd5.png)

**Comment by alansouzati** [comment]
Hi @DanielZhu, thanks for your finding. We have fixed this issue, can you test it again?

By default the button has a `disabled` state if no `onClick` callback is provided.

If you want the button to be active, please add the following:

`<Grommet.Button label="Action" primary={true} strong={true} onClick={this._onClick}></Grommet.Button>`

**Comment by DanielZhu** [comment]
Thanks your quick response, @alansouzati 

I tested it again and it has been fixed. Cool. 
I think you can close this issue.

**Comment by alansouzati** [comment]
Thanks for reporting in the first place.
