### ISSUE TITLE
Buttons are jumping on hover.

### ISSUE THREAD

**Issue by cssberries** [HewlettPackard/grommet#45]
Probably because of the different border widths - normal 2px on hover 3px.
Can be solved by using shadows (multiple insets ) instead of borders.
Or by changing the design to fixed border width.

I think that second option is better.

**Comment by alansouzati** [comment]
Thanks for pointing this our @cssberries. Would be willing to send a PR for this?

**Comment by alansouzati** [comment]
Also, I would like to invite you to our chat tool :smile: 

[![Slack](http://alansouzati.github.io/artic/img/slack-badge.svg)](http://grommet.io/slackin)

**Comment by tobias-flitsch** [comment]
Does box-sizing help instead of playing around with shadows?

**Comment by cssberries** [comment]
Actually, it happens only with the buttons on the home page and caused by larger padding size on hover state.

**Comment by ericsoderberghp** [comment]
FYI, we are revamping the Button styles across the board at the moment.

**Comment by alansouzati** [comment]
Fixed by #46
