### ISSUE TITLE
Broken link to assets

### ISSUE THREAD

**Issue by bryanjacquot** [HewlettPackard/grommet#50]
The link on download page to the AI sticker sheet is broken:
http://grommet.io/assets/latest/grommet_sticker_sheet.ai

`Cannot GET /assets/latest/grommet_sticker_sheet.ai`

Other download assets also appear to be broken.

**Comment by alansouzati** [comment]
Sorry about that. This has been fixed by [d82ffb](https://github.com/HewlettPackard/grommet/commit/d82ffb3bf172e4147d571fa09709d9df96f15321).
