### ISSUE TITLE
adjustBackground() is called even if there is no background image defined (Login Component)

### ISSUE THREAD

**Issue by Thylossus** [HewlettPackard/grommet#51]
Hi,

the function `adjustBackground()` of the [Login Component](https://github.com/HewlettPackard/grommet/blob/master/src/js/components/Login.js) is called even if there is no background image defined. This results in a JavaScript error `Uncaught TypeError: Cannot read property 'getDOMNode' of undefined`. 

The problem is that the `adjustBackground`is bound to the window's resize event without checking whether `this.props.background` is truthy.

It's not a critical error, but I think it would be good to resolve this just to keep the log free from errors. If you have not already solved this issue, I can submit a PR.

**Comment by alansouzati** [comment]
Hi @Thylossus thanks for reporting this. I believe we haven't solved that one yet. So, feel free to send a pull request.

**Comment by alansouzati** [comment]
Solved by #52
