### ISSUE TITLE
Submitting form by pressing Enter in a form field

### ISSUE THREAD

**Issue by Thylossus** [HewlettPackard/grommet#53]
Hi,

I think there is an issue with submitting forms when pressing enter in a form field when there are two buttons (a submit button and a cancel button). I was able to reproduce this issue using the [FullForm](https://github.com/HewlettPackard/grommet/blob/master/docs/src/documentation/components/samples/FullForm.js) example from the docs.

If the user presses enter within a form, the form is not always submitted. Instead the `onClick` action associated to the first button defined within the form's DOM will be executed, i.e. if the submit button is defined before the cancel button, pressing enter will submit the form. However, if the cancel button is defined before the submit button, pressing enter will 'cancel' the form, i.e. execute the `onClick` action associated with the cancel button.

This issue can be observed by changing 

````
<Footer>
  <Menu direction="right">
    <Button label="OK" primary={true} strong={true} onClick={this.props.onSubmit} />
    <Button label="Cancel" onClick={this.props.onCancel} />
  </Menu>
</Footer>
````

to 

````
<Footer>
  <Menu direction="right">
    <Button label="Cancel" onClick={this.props.onCancel} />
    <Button label="OK" primary={true} strong={true} onClick={this.props.onSubmit} />
  </Menu>
</Footer>
````

in the [FullForm](https://github.com/HewlettPackard/grommet/blob/master/docs/src/documentation/components/samples/FullForm.js) sample. (I have also added log messages to [FormDoc](https://github.com/HewlettPackard/grommet/blob/master/docs/src/documentation/components/FormDoc.js) to see which function is executed).

I know this is not really a grommet specific issue, but maybe a hint in the documentation would be useful because in my opinion adding the `primary` attribute to a button suggests that the action associated with a primary button will be the default action when hitting Enter while filling out the form.

I suppose a solution with `<input type="reset">` and `<input type="submit">` as in [this fiddle](http://jsfiddle.net/ngdqko30/) is not a feasible solution for grommet because it would require dedicated "form buttons". That's why I think a hint in the documentation would be sufficient.

**Comment by alansouzati** [comment]
Fixed
