### ISSUE TITLE
Can't generate test coverage on windows.

### ISSUE THREAD

**Issue by tvmj02** [HewlettPackard/grommet#55]
Hi,

I'm trying to generate the test coverage on my windows machine, but every time I run **gulp coverage** I get the error:

```
Test failed: Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

The tests run Ok, but it doesn't generate the coverage report.

**Comment by alansouzati** [comment]
Fixed by #56
