### ISSUE TITLE
grommet export tool does not export outside references

### ISSUE THREAD

**Issue by klausb** [HewlettPackard/grommet#60]
When using the export tool (export medium-app) the resulting app includes references folders outside the exported app, which are not included in the export. As a result the app does not run.

**Comment by alansouzati** [comment]
This should be fixed as part of version 0.3.0. Could you please run `npm update` inside your project and try again?

**Comment by alansouzati** [comment]
Closing this issue for now. Please reopen if you are still facing issues.
