### ISSUE TITLE
Update Intl

### ISSUE THREAD

**Issue by mattfarina** [HewlettPackard/grommet#70]
The `intl` package now has 1.0.0 release candidates. If I use `npm install intl` it installs the release candidate. Something changed so that if you have a 1.0.0 release candidate things break. Should likely update sometime in the near future.

**Comment by alansouzati** [comment]
Will take a look on that.

**Comment by alansouzati** [comment]
Updated! :+1:

**Comment by alansouzati** [comment]
Now we are integrated with David to keep track of our dependencies state.

[![Dependency Status](https://david-dm.org/hewlettpackard/grommet.svg)](https://david-dm.org/hewlettpackard/grommet)  [![devDependency Status](https://david-dm.org/hewlettpackard/grommet/dev-status.svg)](https://david-dm.org/hewlettpackard/grommet#info=devDependencies)
