### ISSUE TITLE
Gulp Build fails : " Unexpected token < You may need an appropriate loader to handle this file type."

### ISSUE THREAD

**Issue by manotoshsil** [HewlettPackard/grommet#74]
Hello,

I have been trying out grommet since couple of weeks back . I had initial build problems but was able to resolve and Start the Example apps.

Recently I cloned the latest grommet source code into a new directory on my local.
Next I followed steps mention in "https://github.com/HewlettPackard/grommet/wiki/Building-Grommet"

Now it fails with errors.   docs , examples all fail with same error while starting up the webpack-server

Apparently Some Loader module is not able to recognize the jsx syntax inside the js files....any suggestion wud b appreciated

<pre>
ERROR in ./src/js/components/index/IndexHistory.js
Module parse failed: C:\ggg\grommet-master\src\js\components\index\IndexHistory.
js Line 103: Unexpected token <
You may need an appropriate loader to handle this file type.
|   render: function () {
|     return (
|       <Chart series={this.state.series || []}
|         xAxis={this.state.xAxis || []}
|         legend={true}
 @ ./examples/medium-app/src/js/MediumDashboard.js 18:19-67

</ pre>

______________
<pre>
ERROR in ./src/js/components/App.js
Module parse failed: C:\ggg\grommet-master\src\js\components\App.js Line 54: Une
xpected token <
You may need an appropriate loader to handle this file type.
|
|     return (
|       <div lang={lang} className={classes.join(' ')}>
|         {children}
|       </div>
 @ ./examples/medium-app/src/js/MediumApp.js 8:10-43

</ pre>

**Comment by alansouzati** [comment]
This should be fixed now, could you please run `npm update` inside your project and try again? Thanks!

**Comment by manotoshsil** [comment]
Thanks. Its fixed now :-)
