### ISSUE TITLE
Datepicker - selected date differs one day from shown date

### ISSUE THREAD

**Issue by klipinski** [HewlettPackard/grommet#75]
URL: http://grommet.io/docs/hpe/develop/calendar
Trying the example on this page, the shown date in the framed box at the bottom of the page is not the selected date from the datepicker. It is always the day before. This bug can be observed with different browsers (IE, FF, Chrome).

**Comment by bryanjacquot** [comment]
I took a look at this using IE and Chrome on Windows and Chrome on Mac and all work correctly.  I'm wondering if there's something going on with your browser/system locale.  What is your primary language set to on your computer/browser?

**Comment by ericsoderberghp** [comment]
It sounds like it might be a timezone issue.

**Comment by klipinski** [comment]
Language is English, timezone is UTC+01:00. I changed also to German, makes no difference. A colleague here in Germany could observe the same, so it is not related only to my machine. Checked it on my machine with Chrome 43.0, Firefox 38.0, Opera 30.0, IE11 in combination with Win7. Also with Android 4.4.2 and Chrome (language in that case German). All show the same effect.

**Comment by klipinski** [comment]
The effect can only be observed in one direction:
1) change the day in the input field, call the datepicker and look to the calendar: the correct date is marked in green. In that direction it works.
2) Other direction: call the datepicker, choose a date and close the calendar: the input field shows the day before the selected day.

There is a JS-warning: "ReferenceError: reference to undefined property this._resizeTimer" in index.js, line 40, col 8596.

**Comment by klipinski** [comment]
Firebug output while executing like described before (case 2):
ReferenceError: reference to undefined property e.fromElement index.js:16:30404
ReferenceError: reference to undefined property r[e] index.js:2:19826
ReferenceError: reference to undefined property r._dispatchListeners index.js:16:22899
ReferenceError: reference to undefined property t[2] index.js:49:3775
ReferenceError: reference to undefined property t._owner index.js:1:19622

**Comment by klipinski** [comment]
Eric, you're right! I changed the timezone to Pacific Time (UTC-08:00). And now it works ... !

**Comment by mirsilstan** [comment]
The bug is caused by the method toISOString, which returns a string representation of a date having the timezone zero UTC offset, as denoted by the suffix "Z".
On the other hand, the calendar is populated with dates having the timezone of the user's machine.
That's why Tue Jul 07 2015 00:00:00 GMT+0300 becomes 2015-07-06T21:00:00.000Z.
I replaced date.toISOString().slice(0, 10) with moment(date).format('YYYY-MM_DD') and it works ok right now.

**Comment by bryanjacquot** [comment]
thanks @mirsilstan, would you mind submitting a PR with your fix?

**Comment by mirsilstan** [comment]
Sure, no problem, I created the pull request #133.
