### ISSUE TITLE
Fonts are not loaded over https

### ISSUE THREAD

**Issue by tobias-flitsch** [HewlettPackard/grommet#77]
If the server is running over https, the fonts are not loaded as the client fails with, e.g.:

```
Mixed Content: The page at 'https://localhost:8443/dashboard/' was loaded over HTTPS, but requested an insecure font 
'http://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGPS42wKzre0cxmO5m5GyTsY.ttf'. This request has been blocked; the content must be served over HTTPS.
```

The fonts are also provided over https, e.g. https://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGPS42wKzre0cxmO5m5GyTsY.ttf change the links in `_settings.font.scss`

**Comment by bryanjacquot** [comment]
Resolved with [#78](https://github.com/HewlettPackard/grommet/pull/78)
