### ISSUE TITLE
online demo please :)?

### ISSUE THREAD

**Issue by winkler1** [HewlettPackard/grommet#79]
Hi-
 Seems like a potentially interesting framework -- is there a representative demo app built with it online? Would like to add it to react.rocks, thanks.

**Comment by bryanjacquot** [comment]
Hi @winkler1.  Thanks for your interest in Grommet.  We have some online demos, but they aren't linked into the site as they should.  We'll fix that.  Until then, feel free to check these out:

 * http://grommet.io - the site itself is using the Grommet framework
 
 * http://grommet.io/medium-app - an example type of a "medium sized" application using Grommet.  Login with any email address and any password.

 * http://grommet.io/cto-app-tuner - a really simple application we used during the launch of Grommet.

 * http://grommet.io/todo-app-modular - we felt obliged to create a ToDo application

**Comment by bryanjacquot** [comment]
Hello again @winkler1.  I've updated the README for each of the example apps to include a links to the live demos.   Would be cool to have Grommet added to react.rocks.  I'd suggest using either the grommet.io site itself, or the medium-app as the example demo app.  Thanks!

**Comment by winkler1** [comment]
Looks good. http://grommet.io/medium-app/login has some nice stuff -- could the login page say any username/password, or even default them so user just has to click? Otherwise, the funnel dropoff would likely be pretty high.

**Comment by bryanjacquot** [comment]
@winkler1, we've updated the Medium App to not require a login.  From the session menu, can logout to return to the Login Page for those who want to interact with it.  Let me know when React.rocks has been updated and we'll promote it.

http://grommet.io/medium-app/

**Comment by rlech** [comment]
seems like there are all down? is there a online example available so see some UI stuff?

**Comment by maysst** [comment]
Demo sites are not available as per links above?

![image](https://cloud.githubusercontent.com/assets/4294542/17214002/dcbf6ae8-54ce-11e6-958d-d46f7bf07d8a.png)

**Comment by alansouzati** [comment]
Sorry,  these links are outdated.

Some demos:

1 - https://hc380.grommet.io (UI for the Hyper Converged 380 from HPE)
2 - http://peoplefinder.grommet.io (source code: https://github.com/grommet/grommet-people-finder, training: https://vimeo.com/173002390)
3 - https://blog.grommet.io (source code: https://github.com/grommet/grommet-blog)
   FYI: we are in the process of redesigning the blog

**Comment by RyanCCollins** [comment]
Hey @winkler1 I've got a few demo apps as well!  The first is a toy app located here: http://restaurant-reviewer-client.herokuapp.com/ .

Coming soon, I have a analytics dashboard and also a homepage for the React Weekly publication, both made with Grommet.  I will share those when available.

**Comment by RainerAtSpirit** [comment]
@RyanCCollins: I was just looking for some examples and found your demo apps. Thanks for sharing!

**Comment by RyanCCollins** [comment]
My pleasure!  Let me know if you have any questions about how they were built.
