### ISSUE TITLE
Server Side Grommet?

### ISSUE THREAD

**Issue by mattfarina** [HewlettPackard/grommet#80]
One of the nice features about React is the virtual DOM. Because of that you can create React apps server side, render them to html, and serve that. This is useful for search engines when your building a site for the general public rather than an app you're logged into.

Grommet 0.2.4 let me build an app like that. Grommet 0.3.0 doesn't. The reason for that is the direct references to the document object from within Grommet components. For example, see the App component that sets the language on the document object. This will just not work on the server side and it circumvents the virtual DOM of Angular.

Should we expect Grommet to only be client side and not used server side? If yes, what's the server side option to be used to be consistent with Grommet and the themes?

**Comment by mattfarina** [comment]
Wanted to give some more background...

**SEO Problem:** If you're building a public website you need to consider SEO. Aside from Google, which in the US has ~67% of the search market, we don't know of other search engines processing all JavaScript.

To solve the front-end built pages while providing SEO tools like [Discourse](http://www.discourse.org/) will serve raw HTML in a `noscript` tag for search engines that don't handle JS. Then do the browser side work separately.

Oh the things we do for SEO. This is important for anyone building a publicly accessible site with Grommet. Apps, especially those behind a login, are different.

In Grommet 0.3.0 the global `document` object is referred to often. You can see this in components like Article. That object is available in browsers but not node.js so Gromment, as it stands today, can't be used to render on the server side.

**Proposed Solution:** Instead of grabbing the global `document` object use the virtual DOM provided by React. Once a component has been rendered to the DOM a read DOM element is associated with a component. Then you can use...
```js
document = React.findDOMNode(this).ownerDocument;
```

**Comment by mattfarina** [comment]
Testing the pattern on #88.

**Comment by alansouzati** [comment]
I believe the main issue before was using `document` inside render function. I've updated the `App` component to move DOM manipulation from `render` to `componentDidMount`. :smile: 

This should be part of the next release but, in the meantime, you can use the [stable](https://github.com/HewlettPackard/grommet/tree/stable) distribution.

```
$ npm install https://github.com/HewlettPackard/grommet.git#stable -g
```

And in your package.json:

```
{
  ...
  dependencies: {
    grommet: "https://github.com/HewlettPackard/grommet.git#stable"
  }
  ...
}
```

Stable means: last commit to the master branch that passed both CI build.

**Comment by mattfarina** [comment]
@alansouzati thanks, I'll take a look. I noticed the `document` object is still referenced in `App.js`. node may still have an issue with an object that's not defined there.

**Comment by alansouzati** [comment]
I think it is ok to have document references outside render function. I tested isomorphic react with todo-app-modular and it works just fine. We do have other references to document elsewhere.

**Comment by alansouzati** [comment]
Closing this issue for now. Please reopen if you still need help with server-side grommet.

**Comment by david-cahill** [comment]
@alansouzati I'm having issues when using the `<Article>` component when server-side rendering, seeing this in the browser console:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) " data-reactid="5"><a tabindex="-1" aria
 (server) " data-reactid="5"></article><span style
```
I'm using v1.6.0, should this work using ssr? Thanks!

**Comment by infiman** [comment]
@david-cahill Same issue here. Have you solved your problem somehow?
