### ISSUE TITLE
Clicking on the green round icon (above the enclosure name) does not display the related details

### ISSUE THREAD

**Issue by tran2519** [HewlettPackard/grommet#94]
Tested on Samsung S4:
In vertical mode, clicking on the green round icon above the enclosure name will display related details
In horizontal mode, no detail is displayed.

![image](https://cloud.githubusercontent.com/assets/13039669/8789399/f1590a30-2ef6-11e5-8f3b-4734b8b1ec77.png)

**Comment by alansouzati** [comment]
Fixed. Thanks for reporting this!
